print('Formulario')
print('Nombre: ')
Nombre = input()
print('Apellido: ')
Apellido = input()
print('Edad: ')
Edad = input()
Sexo = input('Sexo: ')
print('El nombre que ingresaste es:', Nombre)
print('El apellido que ingresaste es:', Apellido)
print('La edad que ingresaste es:', Edad)
print('El sexo es', Sexo)
